/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rosmi' at '02.05.16 21:56' with Gradle 2.13
 *
 * @author rosmi, @date 02.05.16 21:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
